[package]
name = "oeis_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
ureq = { version = "3", features = ["json"] }
rand = "0.9"
num-bigint = "0.4"
